### PR TITLE
Remove encoding option

### PR DESCRIPTION
**Pull request by danmcp**

### CODE REVIEW

**Comment by danmcp** [comment]
@jbernal0019 What do you normally need to do to update pfurl in cube?

**Comment by jbernal0019** [comment]
@danmcp I guess you only need to update the requirements to the latest version of pfurl here:

https://github.com/FNNDSC/ChRIS_ultron_backEnd/blob/master/requirements/base.txt

The docker image will build automatically after the update.

**Comment by danmcp** [comment]
@rudolphpienaar I think that means you are going to have to build it first

**Comment by rudolphpienaar** [comment]
There are some PRs out on pfurl... are they ok to merge? If so I can do all those, update the build and also push out to PyPI

**Comment by danmcp** [comment]
@rudolphpienaar Yeah, I thought I had already merged Chloe's.  The betaredex one should be fine although it won't do anything until his other pulls merge (which are still being tested).

**Comment by danmcp** [comment]
@jbernal0019 Please review

**Comment by danmcp** [comment]
> Not sure why this was set TAG=:dev instead of TAG=:latest in the make file though.

I am happy to change it back if I am wrong.  But my understanding is the dev branch isn't something we are actively using anymore.

**Comment by rudolphpienaar** [comment]
That's all good as far as I'm concerned... LGTM

**Pull request merged**
