### PR TITLE
Added support for parallelized image plugins.

### PR DESCRIPTION
**Pull request by Chris210634**
@rudolphpienaar @jbernal0019 @danmcp,

Three new attributes were added to the plug-in object:
 - NUMBER_OF_WORKERS
 - CPU_LIMIT
 - MEMORY_LIMIT

These values should be specified as class variables when writing the plug-in class, for example:
```
 class AntsReg(ChrisApp):
     """
     A plugin app for registration using ants.
     """
 class AntsReg(ChrisApp):
     """
     A plugin app for registration using ants.
     """
     AUTHORS         = 'FNNDSC (dev@babyMRI.org)'
     SELFPATH        = os.path.dirname(os.path.abspath(__file__))
     SELFEXEC        = os.path.basename(__file__)
     EXECSHELL       = 'python3'
     TITLE           = 'Ants registration'
     CATEGORY        = ''
     TYPE            = 'ds'
     DESCRIPTION     = 'A plugin app for registration using ants'
     DOCUMENTATION   = 'http://wiki'
     VERSION         = '0.1'
     LICENSE         = 'Opensource (MIT)'
     NUMBER_OF_WORKERS = 4
     CPU_LIMIT         = '4000m'
     MEMORY_LIMIT      = '5Gi'
     ...
```

The way you run the plugin from CUBE doesn't change. Every time the plug-in is run, it runs with the parameters specified by its JSON file.

### CODE REVIEW

**Comment by danmcp** [comment]
@jbernal0019 Please give this a look over.  Let us know what else is necessary.

**Comment by jbernal0019** [comment]
Hey guys I think that with this implementation the plugin developer is deciding at development time the resources that a job will use in the cluster rather than the user at run time. Thus a plugin will always run with the same resources for any user.

Not sure that’s the right approach. Usually the user asks for resources when he/she submits a job to a cluster. This doesn’t seem a property of the plugin itself but of the specific plugin instance. 

The plugin can announce minimum/ default values as its requirements though: MIN_NUMBER_OF_WORKERS for instance.

@rudolphpienaar @danmcp what do you think?

**Comment by rudolphpienaar** [comment]
I think it's reasonable for a plugin developer to suggest a set of minimum execution requirements for the plugin. Then, it's up to CHRIS/CUBE to decide how to farm this out (or perhaps the admin to decide which execute env to associate the plugin with).

So I would think that it's ok for a developer to provide of suggested execution env characteristics and that these are part of its descriptor/representation and kept say in the plugin store.

I'm also thinking out loud and on my feet... so I'll stop for now and hear what others think.

**Comment by Chris210634** [comment]
@jbernal0019,

I agree with this. The settings communicated to CUBE during plugin registration should be taken as default values. I will work on a way to let the user override the defaults in their request to run the plugin. This needs to be implemented to test parallel plugins anyhow.  

For your second point, I don't think that the default should be the same as the minimum value, however, there definitely should be a range of allowed values for CPU_LIMIT, MEMORY_LIMIT, and NUMBER_OF_WORKERS. 

I realize this wasn't clear. The CPU_LIMIT is the limit on cpu usage of one pod/worker. The idea is that a plugin might want to run more than one thread in a worker. The plugin will decide how many threads to run within each worker based on the cpu limit.

**Comment by danmcp** [comment]
@jbernal0019 @rudolphpienaar @Chris210634 

This is good conversation and we should probably talk again tomorrow to make sure we are on the same page.  Everything we have talked about so far is:

1) A way for the developer of a plugin to specify min and max values for CPU, Memory, and Num Workers
2) A way to register a plugin with CUBE and specify default values (within the min and max allowed) for a given plugin
3) A way to override the default values as a user of ChRIS.  We recognize that most users wouldn't know the right values.  If we ever do this, we would probably want to expose something simpler to an end user (like high/medium/low priority) and we would translate those values to something between min and max within the frontend or backend.

I think we should wait to do 3) but I am stating it for completeness of the design.

I don't think the implementation matches quite what I have stated yet.  So let's get agreement on the design and we can fixup the implementation to match.

**Comment by jbernal0019** [comment]
Hey @danmcp I will likely not be able to attend the meeting tomorrow (a health issue) but I quite agree with your 3-bullets proposal for the design :)

I think that In addition a plugin developer should also be able to comunicate weather or not a plugin requires/should access the GPU resources.

**Comment by danmcp** [comment]
@jbernal0019 That's a good one as well.  I added an issue to track it: https://github.com/redhat-university-partnerships/radiology/issues/46

This one will be a little more complicated than the CPU/Memory/num_workers since not all GPUs are created equal.

**Comment by Chris210634** [comment]
Hi @jbernal0019 @rudolphpienaar @danmcp ,

I updated this PR to support min and max for number of workers, memory limit, and cpu limit.  A parallel plug-in might specify these values as class variables as such:

'''
AUTHORS         = 'FNNDSC (dev@babyMRI.org)'
    SELFPATH        = os.path.dirname(os.path.abspath(__file__))
    SELFEXEC        = os.path.basename(__file__)
    TITLE           = 'Parallel chris ds app'
    EXECSHELL       = 'python3'
    CATEGORY        = ''
    TYPE            = 'ds'
    DESCRIPTION     = 'A parallel chris ds app demo'
    DOCUMENTATION   = 'http://wiki'
    LICENSE         = 'Opensource (MIT)'
    VERSION         = '0.1'
    MAX_NUMBER_OF_WORKERS = 64
    MIN_NUMBER_OF_WORKERS = 1
    MAX_CPU_LIMIT       = '4000m'
    MIN_CPU_LIMIT       = '1000m'
    MAX_MEMORY_LIMIT    = '8Gi'
    MIN_MEMORY_LIMIT    = '128Mi'
'''
The values are checked on registration and entered into the database. If the values are not specified, then default values are

MAX_NUMBER_OF_WORKERS = 1
MIN_NUMBER_OF_WORKERS = 1 
MAX_CPU_LIMIT       = '2000m'
MIN_CPU_LIMIT       = '2000m'
MAX_MEMORY_LIMIT    = '200Mi'
MIN_MEMORY_LIMIT    = '200Mi'

A plugin can be run through CUBE with the following request:

'''
pfurl --auth chris:chris1234 --verb POST --http ${HOST_IP}:8000/api/v1/plugins/11/instances/ \
--content-type application/vnd.collection+json \
--jsonwrapper 'template' --msg '
{"data":
    [
     {"name":"sleepLength",
      "value":"0"},
     {"name":"prefix",
      "value":"test-"},
     {"name":"previous_id",
      "value":"40"},
     {"name":"number_of_workers",
      "value":"2"},
     {"name":"memory_limit",
      "value":"10Gi"},
     {"name":"cpu_limit",
      "value":"5000m"}
    ]
}' \
--quiet --jsonpprintindent 4
'''

If the optional values are not specified, they default to the min value. If value specified is less than the minimum set by the plugin, the value is set to the min, if it is greater than the max, it is set to the max.

**Comment by danmcp** [comment]
@Chris210634 ^^

**Comment by Chris210634** [comment]
@danmcp @rudolphpienaar @jbernal0019 

Here's my opinion:

For number of workers the MAX needs to be set because certain plug-ins may not work if parallelized across more than x number of machines. For example, a plug-in that is not process parallelized would set the MAX to 1. I can't see a use case where the MIN for number of workers would be greater than one. 

For Memory. The Plug-in developer would probably have a general idea of how much memory a typical use case would need when running the plug-in and would set the MIN accordingly. I agree that the MAX memory should not be set by the plugin developer, since this is up to the system admin to set. 

Similarly, for the CPU limit, I agree that the MAX does not need to be set.

So we would be left with the following:

MAX_NUMBER_OF_WORKERS 
MIN_NUMBER_OF_WORKERS 
MIN_CPU_LIMIT
MIN_MEMORY_LIMIT

**Comment by Chris210634** [comment]
@danmcp 

Right. I think that there is a small fraction of plugins that might make use of each of these max/min settings. 

All plug-ins will function if they are not able to set MAX, but we risk over-allocating resources. 

The drawback of supporting MAX and MIN settings for all three parameters is additional complexity in CUBE.

**Comment by Chris210634** [comment]
@danmcp @jbernal0019 @rudolphpienaar 

I changed this PR slightly:

 - Memory and CPU values are stored as integer values in Mi and millicores respectively. This is so we don't have to convert from string to integer whenever we have to check a input against the min and max.
 - Handle cases when only MIN or only MAX is specified correctly. 
 - Specify defaults for MIN and MAX values

**Comment by Chris210634** [comment]
@danmcp @jbernal0019 @rudolphpienaar 

I changed this PR slightly:

 - Memory and CPU values are stored as integer values in Mi and millicores respectively. This is so we don't have to convert from string to integer whenever we have to check a input against the min and max.
 - Handle cases when only MIN or only MAX is specified correctly. 
 - Specify defaults for MIN and MAX values in models.py, before the defaults were hardcoded in different places.

**Comment by jbernal0019** [comment]
Hey @Chris210634 just a couple of suggestions.  It seems to me that here 

https://github.com/FNNDSC/ChRIS_ultron_backEnd/pull/34/files#diff-dc9a2604c16871003823cafcc7b2fd41R131 

you are performing a validation of request's parameters. Validation code should be in the corresponding serializer and called from the view like this for instance: `previous = serializer.validate_previous(previous_id, plugin)`.

One always must strive to have as light as possible views (views with minimal amount of code). Please modify accordingly. 

Please also check the code for this method: 

https://github.com/FNNDSC/ChRIS_ultron_backEnd/pull/34/files#diff-39460a9de631312e0ee5e0bc74c4312cR187

Too many ifs make it eligible. Probably too many redundant conditions. You might want to try dictionaries and/or exceptions or splitting it into more than one method.These many ifs and nested ifs usually leads to logic errors. For instance this 

https://github.com/FNNDSC/ChRIS_ultron_backEnd/pull/34/files#diff-39460a9de631312e0ee5e0bc74c4312cR204 

might fail not because `app_repr['max_memory_limit'] < app_repr['min_memory_limit']` but because they could both be the empty string for instance.

HTH

**Comment by Chris210634** [comment]
Hi @jbernal0019,

> 
> you are performing a validation of request's parameters. Validation code should be in the corresponding serializer and called from the view like this for instance: previous = serializer.validate_previous(previous_id, plugin).
> 
> One always must strive to have as light as possible views (views with minimal amount of code). Please modify accordingly.

I moved the validation code to serializer as suggested.

> 
> Please also check the code for this method:
> 
> https://github.com/FNNDSC/ChRIS_ultron_backEnd/pull/34/files#diff-39460a9de631312e0ee5e0bc74c4312cR187
> 
> Too many ifs make it eligible. Probably too many redundant conditions. You might want to try dictionaries and/or exceptions or splitting it into more than one method.These many ifs and nested ifs usually leads to logic errors. For instance this

I split this section into three methods. The code still looks ugly, but I'm not sure how to make it look more legible. The if statements all check for various edge cases.

> https://github.com/FNNDSC/ChRIS_ultron_backEnd/pull/34/files#diff-39460a9de631312e0ee5e0bc74c4312cR204
> 
> might fail not because app_repr['max_memory_limit'] < app_repr['min_memory_limit'] but because they could both be the empty string for instance.

You're right, originally the empty string input would have caused an error, I fixed this problem. Now, an empty string means the same thing as not including the parameter in the json at all.

I've also noticed that the migrations file is auto generated. I edited this manually. Is the script that generated the migrations files in the git repo? If it is, I don't think I edited it.

@ravisantoshgudimetla @danmcp FYI

**Comment by jbernal0019** [comment]
@ravisantoshgudimetla @danmcp @rudolphpienaar 

@Chris210634 You must run the `python manage.py makemigrations` within the CUBE container as your local user every time before you make a pull request that modifies the DB models. That will generate the required DB migrations automatically for you. You shouldn't modify the migration files.

There are also many conflicts in this branch. Could you please solve them and remake the PR.
Thanks!

**Comment by Chris210634** [comment]
Don't merge yet.

**Comment by Chris210634** [comment]
@ravisantoshgudimetla, 

Thanks for this information. I made the migrations exactly the way you wrote here. There seems to be an error, I will investigate later today.

**Comment by Chris210634** [comment]
@jbernal0019,

I generated the proper migrations file and resolved merge conflicts. This is ready to merge unless there's anything else you want me to change.

**Comment by jbernal0019** [comment]
cc: @danmcp @rudolphpienaar 

Great work @Chris210634 but I think a bit more is needed:

  `number_of_workers` and `cpu_limit` need to be added to the PluginsInstance's  model and serializer the same way @ravisantoshgudimetla did with `gpu_limit` so the user can set those parameters from the front end at execution time,  and to ensure proper execution of the code in  `validate_number_of_workers` and `validate_cpu_limit` (I think currently those parameters will never be in the request). Could you please check this?

On the other hand @ravisantoshgudimetla `min_gpu_limit` and `max_gpu_limit` need to be added to the fields in PluginSerializer as @Chris210634 did with his parameters otherwise the API will not expose this info. Could you please check this?

Thanks!

**Comment by ravisantoshgudimetla** [comment]
> On the other hand @ravisantoshgudimetla min_gpu_limit and max_gpu_limit need to be added to the fields in PluginSerializer as @Chris210634 did with his parameters otherwise the API will not expose this info. Could you please check this?

Damn, I thought I added them but apparently not. I have created a PR for it #39.

**Comment by Chris210634** [comment]
@ravisantoshgudimetla @jbernal0019 @rudolphpienaar @danmcp 

I finished updating this pull request to fix some issues, here are the changes I made:
 - if user resource request is outside range of min/max, instead of silently altering the request to either min or max, throw validation error.
 - Validation code is not in views any more, it is done in serializer.
 - Max resource limit for any resource defaults to max integer. Min resource limit for number of workers defaults to 1, for gpu limit default to 0, for cpu limit default to 1000m, for memory limit default to 200Mi. It doesn't make sense for the minimum resource of cpu and memory to default to 0 or 1, so I chose values that I thought made sense.
 - I wrote custom model fields for memory and cpu limits, since they don't work well with integer or sting fields.

**Pull request merged**
