### PR TITLE
Plugin registration with compute resource. 

### PR DESCRIPTION
**Pull request by anik120**
Work in progress. Not ready to be merged yet. 

Function signature of add_plugin in manger.py changed from 
add_plugin(self, dock_image_name) to
add_plugin(self, dock_image_name, compute_resource)

### CODE REVIEW

**Comment by danmcp** [comment]
@anik120 Please squash the commits

**Comment by danmcp** [comment]
@jbernal0019 @rudolphpienaar Please review

**Comment by jbernal0019** [comment]
@anik120 is this WIP or ready to review/merge?

**Comment by anik120** [comment]
@jbernal0019 I need a couple of more days before it's ready to be reviewed. Will update as soon as it's ready.

**Comment by anik120** [comment]
@danmcp @rudolphpienaar @jbernal0019 ready to review.

**Comment by danmcp** [comment]
@anik120 It looks like you have a conflict that needs to be resolved.

**Comment by jbernal0019** [comment]
**Hey @anik120 lot of good work here :)**

I have a few suggestions though.

 In https://github.com/FNNDSC/ChRIS_ultron_backEnd/pull/33/files#diff-beffeacb2b2412f6e4e6504dabccbe67R98 I don't think the relation `related_name='compute_resource'` is correctly named. It should probably be `related_name='plugin_instances'`

I don't think that changing in https://github.com/FNNDSC/ChRIS_ultron_backEnd/pull/33/files#diff-39460a9de631312e0ee5e0bc74c4312cL31   `group=parser.add_mutually_exclusive_group()`  to `group=parser.add_argument_group()` is a good solution here. I guess we wanted `--add`, `--remove` and `--modify` flags to be mutually exclusive. In addition the `--computeResource` flag doesn't apply to the `--remove` option. What about  exploring ArgumentParser's subcommands Like `ArgumentParser.add_subparsers`

In https://github.com/FNNDSC/ChRIS_ultron_backEnd/pull/33/files#diff-20ab4e54ba121a7759518cae30006028R48 I don't think it should be an API descriptor but rather a link relation. So it should be a `serializers.HyperlinkedRelatedField` with `read_only=True`

Also watch out what is a  `compute_resource` and what is a `compute_resource_id` like here: https://github.com/FNNDSC/ChRIS_ultron_backEnd/pull/33/files#diff-39460a9de631312e0ee5e0bc74c4312cR123

Please solve the conflict in `docker-destroy-chris_dev.sh` too by accepted the new changes.

**Comment by jbernal0019** [comment]
Hey @anik120 It seems that you need to run `python manage.py makemigrations --merge` to fix a migrations conflict.

**Comment by anik120** [comment]
@danmcp @rudolphpienaar @jbernal0019 

In https://github.com/FNNDSC/ChRIS_ultron_backEnd/pull/33/files#diff-beffeacb2b2412f6e4e6504dabccbe67R98 changed <code>related_name='compute_resource'</code> to <code>related_name='plugin_instances'</code>

In https://github.com/FNNDSC/ChRIS_ultron_backEnd/pull/33/files#diff-39460a9de631312e0ee5e0bc74c4312cL31 reverted back to <code>group=parser.add_mutually_exclusive_group()</code>
add, remove and modify are now mutually exclusive, and a new plugin can be added in the following way: manager.py - -add DockerImageName ComputeResourceIdentifier

In https://github.com/FNNDSC/ChRIS_ultron_backEnd/pull/33/files#diff-20ab4e54ba121a7759518cae30006028R48 changed to <code>serializers.HyperlinkedRelatedField</code> with <code>read_only=True</code>

Also removed default from https://github.com/FNNDSC/ChRIS_ultron_backEnd/pull/33/files#diff-39460a9de631312e0ee5e0bc74c4312cR123 as suggested by @jbernal0019 earlier.

Resolved all conflicts with base branch.

Squashed all commits. The latest commit is to resolve conflict with base branch.

**Comment by jbernal0019** [comment]
Awesome! I' cleanup and fix some minor things after merge (for instance we must allow the manager to change the compute resource with the --modify). But nice work @anik120 !

**Pull request merged**
